### ISSUE TITLE
Duplicated resource logical IDs

### ISSUE THREAD

**Issue by andromeda306** [aws-samples/datamesh-ui#20]
I'm currently going through the [Build a Data Mesh on AWS](https://catalog.us-east-1.prod.workshops.aws/workshops/23e6326b-58ee-4ab0-9bc7-3c8d730eb851/en-US) steps and successfully deployed the Customer and Central stacks within their respective accounts - though I'm yet to have any success with the datamesh-ui amplify deployment.

Nevertheless I'm now running into issues when deploying the LoB stack https://catalog.us-east-1.prod.workshops.aws/workshops/23e6326b-58ee-4ab0-9bc7-3c8d730eb851/en-US/hands-on-lab/lab1/deploy-cdk as cloudformation repeatedly detects that resources with the same Logical ID already exist in the successfully deployed "Customer" stack. Is this intended behaviour?

This is just one example of the issue re DataDomainnracWorkflow20CDBB6B, though I can see it is also present with at least DataDomainDataDomainCrawler83B79D51, DataDomaindataDomainEventBusC7514AF1, DataDomaintbacWorkflowA09269B8,
![obraz](https://user-images.githubusercontent.com/11481305/216569357-7ff8064e-d0a7-454c-9e93-bc99ea8eda75.png)
![obraz](https://user-images.githubusercontent.com/11481305/216569470-30a6dfa7-0276-4708-bb0b-939a105ebad9.png)

**Comment by jmgtan** [comment]
This is the expected output because the Customer and the LoB should be deployed in different accounts. There are 3 accounts for this workshop:

1. Central governance
2. Customer Data Domain which contains the customer related seed data
3. LoB (Sales Data Domain) which is the participant account

Typically, the instructor would deploy Central and Customer accounts prior to the workshop, and the participants would interact with those 2 accounts throughout the workshop. The reason why you're getting this error is because the Customer account uses the same Data Domain constructs. They should be sitting in separate accounts.
